# Generated by Django 2.0.5 on 2018-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='plaid_acct_id',
            field=models.TextField(blank=True, max_length='100'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='subaccount_name',
            field=models.TextField(blank=True, max_length='200'),
        ),
    ]
