# Generated by Django 2.0.5 on 2018-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180503_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loc_city',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loc_zip',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
