# Generated by Django 2.0.5 on 2018-05-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180503_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='loc_city',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loc_zip',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
