# Generated by Django 2.0.5 on 2018-05-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plaid_acct_id',
            field=models.TextField(blank=True, max_length='100'),
        ),
    ]
