# Generated by Django 2.0.5 on 2018-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_transaction_plaid_acct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.TextField(blank=True, max_length='30', null=True),
        ),
    ]
