# Generated by Django 2.0.5 on 2018-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_transaction_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
